[project]
name = "lru-cache"
version = "0.1.0"
requires-python = ">=3.10"
readme = "README.md"
license = {file = "LICENSE"}

[project.optional-dependencies]
test = ["pytest==8.2.0"]

[tool.setuptools]
py-modules = ["lru_cache"]

[tool.setuptools.package-data]
lru_cache = ["py.typed"]

[tool.ruff.lint]
extend-select = ["I", "UP", "LOG", "G", "PT", "SIM", "TCH"]
