[project]
name = "lru-cache"
version = "0.1.0"
requires-python = ">=3.10"
readme = "README.md"
license = {file = "LICENSE"}

[tool.setuptools]
py-modules = ["lru_cache", "py.typed"]

[tool.ruff.lint]
extend-select = ["I", "UP", "LOG", "G", "PT", "SIM", "TCH"]
